Ili9488init changes
nielsnl68/esphome pull request #88
Opened 2023-02-27 15:47 UTC by Rendman

# What does this implement/fix?

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable): N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Checklist:
  - [X ] The code change is tested and works locally.
  - [-] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [- ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-27 18:08 UTC, nielsnl68 commented
First of all thanks for this PR, i'm sure others will love it when they can finally use there ili9488 display(s) with esphome.
Before i can merge it could you please do me a favor and check the errors reported and fix them?

2023-02-28 03:44 UTC, Rendman commented
I think I got them all... I'll check again later to make sure it's successful.

2023-02-28 11:11 UTC, nielsnl68 requested changes
I have one one small request left before i can safely merge it to my branch and update it to the main branch of espHome.

2023-02-28 11:11 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +    ESP_LOGCONFIG(TAG, "  18-Bit Mode: NO");
```suggestion
```
there is no need to tell if it is not in 18bit mode.

2023-02-28 11:11 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +      ESP_LOGVV(TAG, "Send to display(pos:%d, rem:%d, zs:%d)", pos, rem, sz);
```suggestion
      //  ESP_LOGVV(TAG, "Send to display(pos:%d, rem:%d, zs:%d)", pos, rem, sz);
```
This log message will slowdown the esp to much.

2023-02-28 11:11 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +  this->is_18bitdisplay = true;
```suggestion
  this->is_18bitdisplay_ = true;
```

2023-02-28 11:11 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.h
> +  bool is_18bitdisplay = false;
```suggestion
  bool is_18bitdisplay_ = false;
```

2023-02-28 11:19 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +      if (this->is_18bitdisplay) {
```suggestion
      if (this->is_18bitdisplay_) {
```

2023-02-28 21:35 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +      if (this->is_18bitdisplay) {
> Thank you for the hand holding... I'll admit, I'm not sure I have the basics of using CI output to make corrections, especially with the diffs. I'll search around the internet for some tutorials. Hopefully I got everything this time.
> 
No problem, i do the changes by hand myself. because i did not found a way to do it using the CI output diff.

> I appreciate the help. On a side note, were you able to test the code with your own display? I'm curious if your display is bad, or if this will fix it for you.
No, I have have not tested it yet, my display will arrive tomorrow 🤤  i get a whole of displays at hand lately. I hope i will get more donations so i can by more different displays to test out.

2023-02-28 21:38 UTC, nielsnl68 approved these changes

2023-02-28 21:41 UTC, merged